version: '3.8'

services:
  redis:
    image: redis:alpine
    container_name: redis
    ports:
      - "6379:6379"
    networks:
      - viajes-net

  gateway:
    build: ./gateway
    container_name: gateway
    ports:
      - "8080:8080"
    environment:
      - SPRING_DATA_REDIS_HOST=redis
      - SPRING_DATA_REDIS_PORT=6379
    depends_on:
      - redis
      - itinerario
      - reservas
    networks:
      - viajes-net

  itinerario:
    build: ./itinerario
    container_name: itinerario
    ports:
      - "8081:8081"
    networks:
      - viajes-net

  reservas:
    build: ./reservas
    container_name: reservas
    ports:
      - "8082:8082"
    networks:
      - viajes-net

networks:
  viajes-net:
    driver: bridge
